
q_create_db = 'create or replace database TASK_DB;'
q_create_stage = 'use database TASK_DB; create or replace stage my_stage;'
q_create_format_csv = '''CREATE FILE FORMAT "TASK_DB"."PUBLIC".CSV TYPE = 'CSV' COMPRESSION = 'AUTO' FIELD_DELIMITER = ',' RECORD_DELIMITER = '\n' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' TRIM_SPACE = FALSE ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE ESCAPE = 'NONE' ESCAPE_UNENCLOSED_FIELD = 'NONE' DATE_FORMAT = 'AUTO' TIMESTAMP_FORMAT = 'AUTO' NULL_IF = ('NULL');'''

q_create_table = ('CREATE OR REPLACE TABLE "TASK_DB"."PUBLIC".'
                  '"RAW_TABLE" ("_ID" STRING,'
                  ' "IOS_APP_ID" STRING,'
                  ' "TITLE" STRING,'
                  ' "DEV_NAME" STRING,'
                  ' "DEV_IOS_ID" STRING,'
                  ' "IOS_STORE_URL" STRING,'
                  ' "SELLER_OFF_WEBSITE" STRING,'
                  ' "AGE_RATING" STRING,'
                  ' "TOTAL_AVG_RATING" STRING,'
                  ' "TOTAL_NUMBER_OF_RATINGS" STRING,'
                  ' "AVG_RATING_FOR_VERSION" STRING,'
                  ' "NUMBER_RATINGS_FOR_VERSION2" STRING,'
                  ' "ORIG_REL_DATE" STRING,'
                  ' "CUR_VER_REL_DATE" STRING,'
                  ' "PRICE_USD" STRING,'
                  ' "PRIMARY_GENRE" STRING,'
                  ' "ALL_GENRES" STRING,'
                  ' "LANGUAGE" STRING,'
                  ' "DESCRIPTION" STRING);'
                  )

q_put_csv_into_stage = 'use database TASK_DB; PUT file:///home/ivannikalayeu/Documents/data_for_tasks/prep_data.csv @my_stage;'
q_copy_into_table = 'use database TASK_DB; COPY INTO RAW_TABLE FROM @my_stage FILE_FORMAT = CSV ON_ERROR = CONTINUE PURGE = FALSE;'
q_data_from_raw_into_stage = 'CREATE TABLE "TASK_DB"."PUBLIC".stage_table CLONE "TASK_DB"."PUBLIC"."RAW_TABLE";'
q_data_from_stage_into_master = 'CREATE TABLE "TASK_DB"."PUBLIC".master_table CLONE "TASK_DB"."PUBLIC"."STAGE_TABLE";'